### ISSUE TITLE
data.zip

### ISSUE THREAD

**Issue by Bennyggcc** [yingjie7/BiosERC#1]
Hello, where is the data.zip file. Could you provide the document? Thank you!

**Comment by phuongnm94** [comment]
you can find it here (our previous work): https://github.com/yingjie7/per_erc/blob/main/data.zip

**Comment by Bennyggcc** [comment]
> you can find it here (our previous work): https://github.com/yingjie7/per_erc/blob/main/data.zip

Sorry for trouble you again. It seems the dataset lack of the directory 'data/llm_vectors/'. When I run the command 'python src/llm_bio_extract.py', it returns the error as follows. 
![image](https://github.com/user-attachments/assets/be2280d0-197f-4509-8343-5f07bec6f0dc)

It seems the code 'llm_bio_extract.py' does not convert 'meld.valid.json' into 'meld.valid_spdescV2_Llama-2-70b-chat-hf.json' (example). Could you give some guidance?
![image](https://github.com/user-attachments/assets/fe75268d-c8f0-47c1-b8cd-c369e61d2267)

**Comment by phuongnm94** [comment]
Hi, this problem is because the output folder (`llm_vectors/`) does not exist. Please check out my updated code to fix it.
